apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-stack-data
  namespace: redis-memory
  labels:
    app.kubernetes.io/name: redis-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
