apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embeddings-cache
  namespace: redis-memory
  labels:
    app.kubernetes.io/name: embeddings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
